WishlistCoreBundle_NotifyAdmin:
    pattern:  /Notify/Admin
    defaults: { _controller: WishlistCoreBundle:Default:NotifyAdmin }    

WishlistCoreBundle_getItemInfo:
  pattern: /ItemInfo
  defaults: { _controller: WishlistCoreBundle:EntityServices:getItemInfo }

WishlistCoreBundle_forgotpassword:
  pattern: /password/reset/
  defaults: { _controller: WishlistCoreBundle:Default:ResetPassword }