<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnumRepository extends EntityRepository
{
}