<?php

namespace Wishlist\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function addEvent( $name, $type, $datetime, WishlistUser $wishlistUser )
    {
        $newEvent = new Event();
        $newEvent->setName($name);
        $newEvent->setEventType($type);
        $newEvent->setEventDate($datetime);
        $newEvent->setWishlistUser($wishlistUser);

        $this->getEntityManager()->persist($newEvent);
        $this->getEntityManager()->flush();       
    }    
}