<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wishlist\CoreBundle\Entity\FriendRequest;

/**
 * FriendRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRequestRepository extends EntityRepository
{
    public function addFriendRequest(\Wishlist\CoreBundle\Entity\WishlistUser $wishlistUser, $text)
    {
        $newFriendRequest = new FriendRequest();
        $newFriendRequest->setText($text);
        $newFriendRequest->setState(FriendRequest::STATE_UNREAD);
        $newFriendRequest->setWishlistUser($wishlistUser);

        $this->getEntityManager()->persist($newFriendRequest);
        $this->getEntityManager()->flush();
        return $newFriendRequest;
    }
}
