<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wishlist\CoreBundle\Entity\Friendship;
use Wishlist\CoreBundle\Entity\WishlistUser;

/**
 * FrienshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendshipRepository extends EntityRepository
{
    public function addNewFriendship(WishlistUser $userA, WishlistUser $userB)
    {
        $this->addNewFriendLink($userA, $userB);
        $this->addNewFriendLink($userB, $userA);
        
        $this->getEntityManager()->flush();
    }
    
    private function addNewFriendLink(WishlistUser $userA, WishlistUser $userB)
    {
        $friendship = new Friendship();
        
        $friendship->setWishlistUser($userA);
        $friendship->setFriend($userB);
        
        $this->getEntityManager()->persist($friendship);
    }
    
    public function searchFriends(WishlistUser $user, /*string*/ $searchTerm)
    {
        $userRepo = $this->getEntityManager()->getRepository('WishlistCoreBundle:WishlistUser');
        $friends = $userRepo->getFriendsOf($user);
        
        foreach ($friends as $friend)
        {
            if ( (strncmp($friend->getFirstname(), $searchTerm, strlen($searchTerm)) == 0) ||
                 (strncmp($friend->getLastname(), $searchTerm, strlen($searchTerm)) == 0) )
            {
                $results[] = $friend;
            }
        }
        
        return $results;
    }
}