<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wishlist\CoreBundle\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function newItem($name, $price, $link)
    {        
        $newItem = new Item();
        $newItem->setName($name);
        $newItem->setPrice($price);
        $newItem->setLink($link);

        return $this->addItem($newItem);
    }

    public function addItem(Item $newItem)
    {
        // check if item exists in the Item table. If not, add it                
        $itemExists = $this->checkItemExists($newItem);
        
        if(!$itemExists){
            $this->getEntityManager()->persist($newItem);
            $this->getEntityManager()->flush();
            $itemExists = $newItem;           
        }
        
        return $itemExists;
    }
    
    public function checkItemExists($item)
    {
       $em = $this->getEntityManager();       
        
        $q = $em->createQuery('
            SELECT i
            FROM WishlistCoreBundle:Item i
            WHERE i.name = :itemName and i.price = :itemPrice and i.link = :itemLink')
                ->setParameters(array('itemName' => $item->getName(),
                                      'itemPrice' => $item->getPrice(),
                                      'itemLink' => $item->getLink()));
                      
        $itemInDatabase = $q->getOneOrNullResult();  
        return $itemInDatabase;
    }    
}
