<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wishlist\CoreBundle\Entity\Notification;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function addNotification(\Wishlist\CoreBundle\Entity\WishlistUser $wishlistUser, /*int*/ $user, $text)
    {
        $newFriendRequest = new FriendRequest();
        $newFriendRequest->setText($text);
        $newFriendRequest->setState(FriendRequest::STATE_UNREAD);
        $newFriendRequest->setWishlistUser($wishlistUser);
        $newFriendRequest->setUserRequested($user);

        $this->getEntityManager()->persist($newFriendRequest);
        $this->getEntityManager()->flush();
        return $newFriendRequest;
    }
}
