<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wishlist\CoreBundle\Entity\Notification;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function addNotification(\Wishlist\CoreBundle\Entity\WishlistUser $wishlistUser, $text)
    {
        $newNotification = new Notification();
        $newNotification->setText($text);
        $newNotification->setState(Notification::STATE_UNREAD);
        $newNotification->setWishlistUser($wishlistUser);

        $this->getEntityManager()->persist($newNotification);
        $this->getEntityManager()->flush();
        return $newNotification;
    }
}
