<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wishlist\CoreBundle\Entity\Token;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
    public function addNewToken($token, $tokenType, $user)
    {
        // first check if a token of this type for this user already exists
        $tokens = $this->findByUser($user->getWishlistuserId());
        
        for($i = 0; $i < count($tokens); $i++){
            if($tokens[$i]->getTokenType() == $tokenType)
            {
                return $tokens[$i]; // already exists
            }
        }
        
        $t = new Token();
        $t->setToken($token);
        $t->setTokenType($tokenType);
        $t->setUser($user);
        $t->setLastUpdated(new \DateTime('now'));

        if(!isset($t))
        {
            return;
        }

        $em = $this->getEntityManager();
        $em->persist($t);
        $em->flush();
        
        return $t;
    }   
    
    public function removeToken($token)
    {
        $this->getEntityManager()->remove($token);
        $this->getEntityManager()->flush();        
    }
}