<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Wishlist\CoreBundle\Entity\WishlistItem;
use Wishlist\CoreBundle\Entity\WishlistUser;

/**
 * WishlistItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistItemRepository extends EntityRepository
{
    public function addItem( $name, $price, $link, $isPublic, $comment, $quantity, WishlistUser $wishlistUser)
    {
        $newItem = new WishlistItem();
        $newItem->setName($name);
        $newItem->setPrice($price);
        $newItem->setLink($link);
        $newItem->setIsPublic($isPublic);
        $newItem->setComment($comment);
        $newItem->setQuantity($quantity);
        $newItem->setWishlistUser($wishlistUser);
        
        $this->getEntityManager()->persist($newItem);
        $this->getEntityManager()->flush();
    }
    
    public function deleteItem( $deletedItemName, WishlistUser $wishlistUser)
    {
        $em = $this->getEntityManager();
        
//        $criteria = array('name' => $deletedItemName);
        
        $q = $em->createQuery('
            SELECT i
            FROM WishlistCoreBundle:WishlistItem i
            LEFT JOIN i.wishlistUser usr
            WHERE i.name = :itemName AND usr.wishlistuser_id = :userId')
                ->setParameters(array('itemName' => $deletedItemName, 'userId' => $wishlistUser->getWishlistuserId()));
        
               
//        $itemToDelete = $this->findOneBy($criteria);
        $itemToDelete = $q->getOneOrNullResult();
        $em->remove($itemToDelete);
        $em->flush();                
    }
}