<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishlistUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistUpdateRepository extends EntityRepository
{
}