<?php

namespace Wishlist\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishlistUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistUserRepository extends EntityRepository
{
    public function getUser($fullname)
    {
        $name = explode(" ", $fullname);
        $first = $name[0];
        $last = $name[1];
        
        return $this->findOneBy(array('firstname' => $first, 'lastname' => $last));
    }
    
    public function validateEmailAndPassword( $email, $password )
    {
        try
        {                                                    
            $q = $this->getEntityManager()
                    ->createQuery('SELECT w FROM WishlistCoreBundle:WishlistUser w WHERE w.email = :email AND w.password = :password')
                    ->setParameter('email', $email)
                    ->setParameter('password', $password);
            
            $userQueryResults = $q->getResult();
            
            $userId = 0;
                        
            foreach ($userQueryResults as $user)
            {
                $userId = $user->getWishlistuserId();
            }        
            
            return $userId;
        }catch(Exception $e)
        {
            return 0;
        }
    }    
}