<?php

/**
 * BaseEnum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $value
 * @property string $type
 * @property Doctrine_Collection $WishlistUser
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getValue()        Returns the current record's "value" value
 * @method string              getType()         Returns the current record's "type" value
 * @method Doctrine_Collection getWishlistUser() Returns the current record's "WishlistUser" collection
 * @method Enum                setName()         Sets the current record's "name" value
 * @method Enum                setValue()        Sets the current record's "value" value
 * @method Enum                setType()         Sets the current record's "type" value
 * @method Enum                setWishlistUser() Sets the current record's "WishlistUser" collection
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('enum');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WishlistUser', array(
             'local' => 'value',
             'foreign' => 'gender'));
    }
}