<?php

/**
 * BaseFriendship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usera_id
 * @property integer $userb_id
 * 
 * @method integer    getUseraId()  Returns the current record's "usera_id" value
 * @method integer    getUserbId()  Returns the current record's "userb_id" value
 * @method Friendship setUseraId()  Sets the current record's "usera_id" value
 * @method Friendship setUserbId()  Sets the current record's "userb_id" value
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriendship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friendships');
        $this->hasColumn('usera_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('userb_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}