<?php

/**
 * BaseUserFriendship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $wishlistuser_id
 * @property integer $friendship_id
 * 
 * @method integer        getWishlistuserId()  Returns the current record's "wishlistuser_id" value
 * @method integer        getFriendshipId()    Returns the current record's "friendship_id" value
 * @method UserFriendship setWishlistuserId()  Sets the current record's "wishlistuser_id" value
 * @method UserFriendship setFriendshipId()    Sets the current record's "friendship_id" value
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserFriendship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_friendship');
        $this->hasColumn('wishlistuser_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('friendship_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}