<?php

/**
 * Baseevents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $wishlistuser_id
 * @property datetime $event_date
 * @property integer $event_type
 * @property WishlistUser $WishlistUser
 * 
 * @method integer      getWishlistuserId()  Returns the current record's "wishlistuser_id" value
 * @method datetime     getEventDate()       Returns the current record's "event_date" value
 * @method integer      getEventType()       Returns the current record's "event_type" value
 * @method WishlistUser getWishlistUser()    Returns the current record's "WishlistUser" value
 * @method events       setWishlistuserId()  Sets the current record's "wishlistuser_id" value
 * @method events       setEventDate()       Sets the current record's "event_date" value
 * @method events       setEventType()       Sets the current record's "event_type" value
 * @method events       setWishlistUser()    Sets the current record's "WishlistUser" value
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseevents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('events');
        $this->hasColumn('wishlistuser_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('event_date', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('event_type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WishlistUser', array(
             'local' => 'wishlistuser_id',
             'foreign' => 'wishlistUser_id',
             'onDelete' => 'CASCADE'));
    }
}