<?php

/**
 * BaseFriendship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $friendship_id
 * @property Doctrine_Collection $WishlistUsers
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getFriendshipId()  Returns the current record's "friendship_id" value
 * @method Doctrine_Collection getWishlistUsers() Returns the current record's "WishlistUsers" collection
 * @method Friendship          setName()          Sets the current record's "name" value
 * @method Friendship          setFriendshipId()  Sets the current record's "friendship_id" value
 * @method Friendship          setWishlistUsers() Sets the current record's "WishlistUsers" collection
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriendship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friendships');
        $this->hasColumn('name', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('friendship_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WishlistUser as WishlistUsers', array(
             'refClass' => 'UserFriendship',
             'local' => 'friendship_id',
             'foreign' => 'wishlistuser_id'));
    }
}