<?php

/**
 * BaseWishlistUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $gender
 * @property integer $age
 * @property string $email
 * @property integer $wishlistuser_id
 * @property Enum $Enum
 * @property Doctrine_Collection $WishlistItems
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method integer             getGender()          Returns the current record's "gender" value
 * @method integer             getAge()             Returns the current record's "age" value
 * @method string              getEmail()           Returns the current record's "email" value
 * @method integer             getWishlistuserId()  Returns the current record's "wishlistuser_id" value
 * @method Enum                getEnum()            Returns the current record's "Enum" value
 * @method Doctrine_Collection getWishlistItems()   Returns the current record's "WishlistItems" collection
 * @method WishlistUser        setName()            Sets the current record's "name" value
 * @method WishlistUser        setGender()          Sets the current record's "gender" value
 * @method WishlistUser        setAge()             Sets the current record's "age" value
 * @method WishlistUser        setEmail()           Sets the current record's "email" value
 * @method WishlistUser        setWishlistuserId()  Sets the current record's "wishlistuser_id" value
 * @method WishlistUser        setEnum()            Sets the current record's "Enum" value
 * @method WishlistUser        setWishlistItems()   Sets the current record's "WishlistItems" collection
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWishlistUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wishlist_user');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('gender', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 1,
             ));
        $this->hasColumn('age', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 18,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('wishlistuser_id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Enum', array(
             'local' => 'gender',
             'foreign' => 'value'));

        $this->hasMany('WishlistItem as WishlistItems', array(
             'local' => 'wishlistUser_id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}