<?php

/**
 * BaseWishlistItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $price
 * @property string $link
 * @property boolean $is_public
 * @property string $comment
 * @property integer $quantity
 * @property integer $user_id
 * @property WishlistUser $WishlistUser
 * 
 * @method string       getName()         Returns the current record's "name" value
 * @method integer      getPrice()        Returns the current record's "price" value
 * @method string       getLink()         Returns the current record's "link" value
 * @method boolean      getIsPublic()     Returns the current record's "is_public" value
 * @method string       getComment()      Returns the current record's "comment" value
 * @method integer      getQuantity()     Returns the current record's "quantity" value
 * @method integer      getUserId()       Returns the current record's "user_id" value
 * @method WishlistUser getWishlistUser() Returns the current record's "WishlistUser" value
 * @method WishlistItem setName()         Sets the current record's "name" value
 * @method WishlistItem setPrice()        Sets the current record's "price" value
 * @method WishlistItem setLink()         Sets the current record's "link" value
 * @method WishlistItem setIsPublic()     Sets the current record's "is_public" value
 * @method WishlistItem setComment()      Sets the current record's "comment" value
 * @method WishlistItem setQuantity()     Sets the current record's "quantity" value
 * @method WishlistItem setUserId()       Sets the current record's "user_id" value
 * @method WishlistItem setWishlistUser() Sets the current record's "WishlistUser" value
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWishlistItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wishlist_item');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('comment', 'string', 500, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 500,
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('item_user', array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'user_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WishlistUser', array(
             'local' => 'user_id',
             'foreign' => 'wishlistUser_id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}