<?php

/**
 * BaseFriendship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userA_id
 * @property integer $userB_id
 * 
 * @method integer    getUserAId()  Returns the current record's "userA_id" value
 * @method integer    getUserBId()  Returns the current record's "userB_id" value
 * @method Friendship setUserAId()  Sets the current record's "userA_id" value
 * @method Friendship setUserBId()  Sets the current record's "userB_id" value
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriendship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friendships');
        $this->hasColumn('userA_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('userB_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}