WishlistFrontpageBundle_homepage:
    pattern:  /Frontpage
    defaults: { _controller: WishlistFrontpageBundle:Default:index }

WishlistFrontpageBundle_navBarTest:
  pattern: /navBar/{username}
  defaults: { _controller: WishlistFrontpageBundle:Default:navBar }
  
Validate:
  pattern: /Frontpage/validateLogin
  defaults: { _controller: WishlistFrontpageBundle:Default:validateLogin }
  
WishlistFrontpageBundle_requestInvite:
  pattern: /Frontpage/requestInvite
  defaults: { _controller: WishlistFrontpageBundle:Default:requestInvite }  
