WishlistFrontpageBundle_homepage:
    pattern: /
    defaults: { _controller: WishlistFrontpageBundle:Default:index }

WishlistFrontpageBundle_navBarTest:
  pattern: /navBar/{username}
  defaults: { _controller: WishlistFrontpageBundle:Default:navBar }
  
Validate:
  pattern: /Frontpage/validateLogin
  defaults: { _controller: WishlistFrontpageBundle:Default:validateLogin }
  
RequestInvite:
  pattern: /Frontpage/requestInvite
  defaults: { _controller: WishlistFrontpageBundle:Default:requestInvite }  
