WishlistFrontpageBundle_homepage:
    pattern:  /Frontpage
    defaults: { _controller: WishlistFrontpageBundle:Default:index }

WishlistFrontpageBundle_navBarTest:
  pattern: /navBar/{username}
  defaults: { _controller: WishlistFrontpageBundle:Default:navBar }