WishlistFrontpageBundle_homepage:
    pattern: /
    defaults: { _controller: WishlistFrontpageBundle:Default:index }

WishlistFrontpageBundle_logout:
  pattern: /logout
  defaults: { _controller: WishlistFrontpageBundle:Default:logout }

Validate:
  pattern: /Frontpage/validateLogin
  defaults: { _controller: WishlistFrontpageBundle:Default:validateLogin }
  
RequestInvite:
  pattern: /Frontpage/requestInvite
  defaults: { _controller: WishlistFrontpageBundle:Default:requestInvite }
