WishlistUserBundle_homepage:
  pattern: /Homepage
  defaults: { _controller: WishlistUserBundle:Default:showHomepage}

WishlistUserBundle_shoppinglist:
  pattern: /Shoppinglist
  defaults: { _controller: WishlistUserBundle:Default:showShoppinglistPage}

WishlistUserBundle_userpage:
  pattern: /User/{user_id}
  defaults: { _controller: WishlistUserBundle:Default:showUserpage}
  
WishlistUserBundle_friendlist:
  pattern: /Friendpage
  defaults: { _controller: WishlistUserBundle:Default:showFriendpage}
  
WishlistUserBundle_friendSearch:
  pattern: /FriendSearch
  defaults: { _controller: WishlistUserBundle:Default:friendSearch }
  
WishlistUserBundle_friendAdd:
  pattern: /FriendAdd
  defaults: { _controller: WishlistUserBundle:Default:friendAdd }

WishlistUserBundle_unfriend:
  pattern: /Unfriend
  defaults: { _controller: WishlistUserBundle:Default:unfriend }

WishlistUserBundle_friendInvite:
  pattern: /FriendInvite
  defaults: { _controller: WishlistUserBundle:Default:friendInvite }

WishlistUserBundle_acceptFriendRequest:
  pattern: /FriendRequestAccept/{notificationId}
  defaults: { _controller: WishlistUserBundle:Default:friendRequestAccept }

WishlistUserBundle_ignoreFriendRequest:
  pattern: /FriendRequestIgnore/{notificationId}
  defaults: { _controller: WishlistUserBundle:Default:friendRequestIgnore }

WishlistUserBundle_accountsettings:
  pattern: /AccountSettings
  defaults: { _controller: WishlistUserBundle:Default:showAccountSettings}
  
WishlistUserBundle_accountsettingsUploadImage:
  pattern: /UploadUserImage
  defaults: { _controller: WishlistUserBundle:Default:uploadUserImage }
  
WishlistUserBundle_save_account_settings:
  pattern: /SaveAccountSettings
  defaults: { _controller: WishlistUserBundle:Default:saveAccountSettings }
  
WishlistUserBundle_lifeEventsManager:
  pattern: /LifeEventsManager
  defaults: { _controller: WishlistUserBundle:Default:showLifeEventsManager }

WishlistUserBundle_saveEvent:
  pattern: /SaveEvent
  defaults: { _controller: WishlistUserBundle:Default:saveEvent }
  
WishlistUserBundle_removeEvent:
  pattern: /RemoveEvent
  defaults: { _controller: WishlistUserBundle:Default:removeEvent }  

WishlistUserBundle_newAccountUser:
  pattern: /NewAccountUser
  defaults: { _controller: WishlistUserBundle:Default:newAccountUser }

WishlistUserBundle_newAccountFriend:
  pattern: /NewAccountFriend
  defaults: { _controller: WishlistUserBundle:Default:newAccountFriend }

