WishlistUserBundle_homepage:
  pattern: /Homepage
  defaults: { _controller: WishlistUserBundle:Default:showHomepage}

WishlistUserBundle_shoppinglist:
  pattern: /Shoppinglist
  defaults: { _controller: WishlistUserBundle:Default:showShoppinglistPage}

WishlistUserBundle_userpage:
  pattern: /User/{user_id}
  defaults: { _controller: WishlistUserBundle:Default:showUserpage}
  
WishlistUserBundle_friendlist:
  pattern: /Friendpage/{user_id}
  defaults: { _controller: WishlistUserBundle:Default:showFriendpage}

WishlistUserBundle_accountsettings:
  pattern: /AccountSettings/{user_id}
  defaults: { _controller: WishlistUserBundle:Default:showAccountSettings}