WishlistUserBundle_homepage:
  pattern: /Homepage
  defaults: { _controller: WishlistUserBundle:Default:showHomepage}

WishlistUserBundle_shoppinglist:
  pattern: /Shoppinglist
  defaults: { _controller: WishlistUserBundle:Default:showShoppinglistPage}

WishlistUserBundle_userpage:
  pattern: /User/{user_id}
  defaults: { _controller: WishlistUserBundle:Default:showUserpage}
  
WishlistUserBundle_friendlist:
  pattern: /Friendpage/{user_id}
  defaults: { _controller: WishlistUserBundle:Default:showFriendpage}

WishlistUserBundle_accountsettings:
  pattern: /AccountSettings
  defaults: { _controller: WishlistUserBundle:Default:showAccountSettings}
  
WishlistUserBundle_accountsettingsUploadImage:
  pattern: /UploadUserImage
  defaults: { _controller: WishlistUserBundle:Default:uploadUserImage }
  
WishlistUserBundle_save_account_settings:
  pattern: /SaveAccountSettings
  defaults: { _controller: WishlistUserBundle:Default:saveAccountSettings }
  
WishlistUserBundle_lifeEventsManager:
  pattern: /LifeEventsManager
  defaults: { _controller: WishlistUserBundle:Default:showLifeEventsManager }