WishlistUserBundle_homepage:
  pattern: /Homepage
  defaults: { _controller: WishlistUserBundle:Default:showHomepage}

WishlistUserBundle_userpage:
  pattern: /User/{user_id}
  defaults: { _controller: WishlistUserBundle:Default:showUserpage}
  
WishlistUserBundle_friendlist:
  pattern: /Friendlist
  defaults: { _controller: WishlistUserBundle:Default:showFriendlist}
  