Wishlist\CoreBundle\Entity\FriendRequest:
  type: entity
  table: null
  repositoryClass: Wishlist\CoreBundle\Repository\FriendRequestRepository
  manyToOne:
    wishlistUser:
      targetEntity: WishlistUser
      inversedBy: notifications
      joinColumn:
        name: user_id
        referencedColumnName: wishlistuser_id
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    state:
      type: integer
    text:
      type: string
      length: 255
  lifecycleCallbacks: {  }
