Wishlist\CoreBundle\Entity\FriendInvite:
  type: entity
  table: null
  repositoryClass: Wishlist\CoreBundle\Repository\NotificationRepository
  manyToOne:
    UserInvited:
      targetEntity: WishlistUser
      inversedBy: friendInvites
      joinColumn:
        name: invitedUserId
        referencedColumnName: wishlistuser_id
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    email:
      type: string

