Wishlist\CoreBundle\Entity\Friendship:
  type: entity
  repositoryClass: Wishlist\CoreBundle\Repository\FriendshipRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    usera_id:
      type: integer
    userb_id:
      type: integer