Wishlist\CoreBundle\Entity\Item:
  type: entity
  table: null
  repositoryClass: Wishlist\CoreBundle\Repository\ItemRepository

  # the following oneToMany relationship definitions are not required but will 
  # help us to easily grab these lists using php classes instead of writing our own queries.
  
  oneToMany:
    wishlistItems: 
      targetEntity: WishlistItem
      mappedBy: Item  

  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: '255'
    price:
      type: integer
      length: null
    link:
      type: string
      length: '255'
    asin:
      type: integer
      nullable: true
    smallImage:
      type: text
      nullable: true
    mediumImage:
      type: text
      nullable: true
    LargeImage:
      type: text
      nullable: true
  lifecycleCallbacks: {  }
