Wishlist\CoreBundle\Entity\Purchase:
  type: entity
  table: null
  repositoryClass: Wishlist\CoreBundle\Repository\PurchaseRepository
  manyToOne:
    user:
      targetEntity: WishlistUser
      joinColumn:
        name: user_id
        referencedColumnName: wishlistuser_id
        
    event:
      targetEntity: Event
      joinColumn:
        name: event_id
        referencedColumnName: id
  
  oneToOne:
    item:
      targetEntity: Item
      inversedBy: purchase
      joinColumn:
        name: item_id
        referencedColumnName: id
            
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    gift_date:
      type: date
      nullable: true
  lifecycleCallbacks: {  }
