Wishlist\CoreBundle\Entity\Request:
  type: entity
  table: null
  repositoryClass: Wishlist\CoreBundle\Repository\RequestRepository
  manyToOne:
    userInvited:
      targetEntity: WishlistUser
      inversedBy: friendsRequested
      joinColumn:
        name: invitedUserId
        referencedColumnName: wishlistuser_id  
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    email:
      type: string
      length: '255'
  lifecycleCallbacks: {  }
