Wishlist\CoreBundle\Entity\WishlistUser:
  type: entity
  oneToMany:
    
    # the following oneToMany relationship definitions are not required but will 
    # help us to easily grab these lists using php classes instead of writing our own queries.
    
    friendships:
      targetEntity: Friendship
      mappedBy: wishlistUser
    
    friendsRequested:
      targetEntity: Request
      mappedBy: userInvited

    events:
      targetEntity: Event
      mappedBy: wishlistUser

    notifications:
      targetEntity: Notification
      mappedBy: wishlistUser

    wishlistItems: 
      targetEntity: WishlistItem
      mappedBy: wishlistUser
      
    purchases:
      targetEntity: Purchase
      mappedBy: wishlistUser
      
    wishlistUpdates:
      targetEntity: WishlistUpdate
      mappedBy: wishlistUser
  repositoryClass: Wishlist\CoreBundle\Repository\WishlistUserRepository

  fields:
    wishlistuser_id:
      id: true
      type: integer
      generator: { strategy: AUTO }    
    name:
      type: string
    birthdate:
      type: datetime
    email:
      type: string
    password:
      type: string
    gender:
      type: integer
