Wishlist\CoreBundle\Entity\WishlistUser:
  type: entity
  ManyToOne:
    gender:
      type: integer
      targetEntity: Enum
  oneToMany:
    friendships:
      targetEntity: WishlistUser
      mappedBy: Friendship

    wishlistItems:
      targetEntity: WishlistItem
      mappedBy: wishlistUser
      
    wishlistUpdates:
      targetEntity: WishlistUpdate
      mappedBy: wishlistUser
  repositoryClass: Wishlist\CoreBundle\Repository\WishlistUserRepository
  id:
    wishlistuser_id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    firstname:
      type: string
    lastname:
      type: string
    birthdate:
      type: datetime
    email:
      type: string
    password:
      type: string    
