Wishlist\CoreBundle\Entity\WishlistItem:
  type: entity
  table: null
  repositoryClass: Wishlist\CoreBundle\Repository\WishlistItemRepository
  manyToOne:
    wishlistUser:
      targetEntity: WishlistUser
      inversedBy: wishlistItems
      joinColumn:
        name: user_id
        referencedColumnName: wishlistuser_id
        
    item:
      targetEntity: Item
      inversedBy: wishlistItems
      joinColumn: 
        name: item_id
        referencedColumnName: id
        
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    is_public:
      type: boolean
      length: null
    comment:
      type: string
      length: '500'
    quantity:
      type: integer
      length: null            
  lifecycleCallbacks: {  }
  