Wishlist\CoreBundle\Entity\WishlistItem:
  type: entity
  table: null
  repositoryClass: Wishlist\CoreBundle\Repository\WishlistItemRepository
  manyToOne:
    wishlistUser:
      targetEntity: WishlistUser
      inversedBy: wishlistItems
      joinColumn:
        name: user_id
        referencedColumnName: wishlistuser_id
   
#  oneToOne:               
#    purchase:
#      targetEntity: Purchase
#      mappedBy: item
        
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    item:
      type: integer
      length: null
  lifecycleCallbacks: {  }
  