Wishlist\CoreBundle\Entity\WishlistUser:
  type: entity
  oneToMany:
    friendships:
      targetEntity: Friendship
      mappedBy: wishlistUser

    events:
      targetEntity: Event
      mappedBy: wishlistUser

    wishlistItems: 
      targetEntity: WishlistItem
      mappedBy: wishlistUser
      
    purchases:
      targetEntity: Purchase
      mappedBy: wishlistUser
      
    wishlistUpdates:
      targetEntity: WishlistUpdate
      mappedBy: wishlistUser
  repositoryClass: Wishlist\CoreBundle\Repository\WishlistUserRepository

  fields:
    wishlistuser_id:
      id: true
      type: integer
      generator: { strategy: AUTO }    
    firstname:
      type: string
    lastname:
      type: string
    birthdate:
      type: datetime
    email:
      type: string
    password:
      type: string
    gender:
      type: integer
