<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/22 20:02:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=wishlist',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
