<?php

/**
 * EventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Events');
    }
}