<?php

/**
 * FriendshipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FriendshipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FriendshipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Friendship');
    }
}