<?php

/**
 * PendingUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PendingUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PendingUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PendingUser');
    }
    
    public static function addPendingUser( $email )
    {
       $new_pendingUser = new PendingUser();
       $new_pendingUser->setEmail($email);       
       $new_pendingUser->save();
    }
}