<?php

/**
 * UpdatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpdatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UpdatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Updates');
    }
}