<?php

/**
 * UserFriendshipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserFriendshipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserFriendshipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserFriendship');
    }

    public function getFriendsOf( $user_id )
    {
        $q = $this->createQuery("c")
                ->where('wishlistuser_id = ?', $user_id);


        $friendships = $q->execute();

        foreach ($friendships as $friendship) {
            $id = $friendship->getFriendshipId();

            $q = $this->createQuery('c')->where('wishlistuser_id != ?', $user_id)->where('friendship_id = ?', $friendship->getFriendshipId());
            $friendUserFriends[] = $q->execute();
        }

    }
}