<?php

/**
 * UserFriendshipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserFriendshipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserFriendshipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserFriendship');
    }
}