<?php

/**
 * wishlist_update
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class wishlist_update extends Basewishlist_update
{
    public function getFormattedTimestamp()
    {
        $now = time();
        $submitted = new DateTime($this->getDateTime());
        $submittedTimeStamp = $submitted->getTimestamp();
        
        $seconds = $now - $submittedTimeStamp;
        $minutes = intval($seconds / 60);
        $hours = intval($minutes / 60);
        $days = intval($hours / 24);
        $weeks = intval($days / 7);  
        
        if( $weeks > 1) // just show the full date
        {
            return date(  "F j, Y, g:i a", $submittedTimeStamp);            
        }
        
        if( $weeks > 0 )
        {
            return $weeks." weeks ago";
            
        }else if( $days > 0 )
        {
            if($days >= 1 && $days < 2)
            {
                return " yesterday";
            }
            
            return $days." days ago";
            
        }else if( $hours > 0 )
        {
            return $hours." hours ago";
        }else if( $minutes > 0 )
        {
            return $minutes." minutes ago";
        }else
        {
            return $seconds." seconds ago";
        }
    }
}
