<?php

/**
 * WishlistUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    wishlist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WishlistUser extends BaseWishlistUser
{
    public function getAge()
    {
        $now = new DateTime('now');

        $diff = date_diff($now, $this->getDateTimeObject('birthdate'));
        return $diff->y;
    }

    public function getGenderString()
    {
        $gender = parent::getGender();

        if($gender == 0)
        {
            return "Male";
        }else {
            return "Female";
        }
    }
}
