<?php

/**
 * WishlistItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WishlistItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WishlistItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WishlistItem');
    }
}