<?php

/**
 * WishlistUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WishlistUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WishlistUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WishlistUser');
    }
}