<?php

/**
 * wishlist_updateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class wishlist_updateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object wishlist_updateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('wishlist_update');
    }
}