<?php

/**
 * WishlistUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WishlistUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WishlistUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WishlistUser');
    }    
    
    public static function validateUser( $email, $password )
    {        
        $q = $this->createQuery()
            ->where('usera_id = ?', $user)
            ->andWhere('usera_id = ?');
       
       /*
       $new_pendingUser = new PendingUser();
       $new_pendingUser->setEmail($email);       
       $new_pendingUser->save();
       */
    } 
    
}