<?php

/**
 * WishlistUpdateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WishlistUpdateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WishlistUpdateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WishlistUpdate');
    }
    
    public function getFriendsUpdates($userId)
    {                                           
        $q = Doctrine_Query::create() 
                ->select("u.id, u.template, u.type, u.message, u.datetime, u.user_id, concat(usr.firstname,' ',usr.lastname)")
                ->from('WishlistUpdate u')
                ->leftJoin('u.WishlistUser usr') 
                ->where('u.user_id IN ( select userb_id from friendships where usera_id = ?)',$userId)               
                ->orderBy('datetime desc');
        
        $t = $q->getSqlQuery();
       
        $updates = $q->execute();
        
        return $updates;
    }
}