# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

wishlist_show:
  url: /wishlist/:wishlistuser_id/
  param: { module: wishlist, action: show }

user_show:
  url: /user/:wishlistuser_id/
  param: { module: user, action: show }

friendlist_show:
  url:   /friendlist/:wishlistuser_id
  param: { module: friendlist, action: index }
  
homepage_show:
  url: /homepage/:wishlistuser_firstname/:wishlistuser_id
  param: { module: homepage, action: index }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default_index_stupid:
  url:   /:module/
  param: { action: index }

default:
  url:   /:module/:action/*
