WishlistDialogBundle:
    resource: "@WishlistDialogBundle/Resources/config/routing.yml"
    prefix:   /

WishlistQABundle:
    resource: "@WishlistQABundle/Resources/config/routing.yml"
    prefix:   /

WishlistListBundle:
    resource: "@WishlistListBundle/Resources/config/routing.yml"
    prefix:   /

WishlistUserBundle:
    resource: "@WishlistUserBundle/Resources/config/routing.yml"
    prefix:   /

WishlistCoreBundle:
    resource: "@WishlistCoreBundle/Resources/config/routing.yml"

WishlistFriendlistBundle:
    resource: "@WishlistFriendlistBundle/Resources/config/routing.yml"
    prefix:   /

WishlistFrontpageBundle:
    resource: "@WishlistFrontpageBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
