WishlistCoreBundle:
    resource: "@WishlistCoreBundle/Resources/config/routing.yml"
    prefix:   /

WishlistFrontpageBundle:
    resource: "@WishlistFrontpageBundle/Resources/config/routing.yml"
    prefix:   /

WishlistHomepageBundle:
    resource: "@WishlistHomepageBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
