WishlistListBundle_wishlistNew:
  pattern: /wishlistnew
  defaults: { _controller: WishlistListBundle:Wishlist:newWishlist }

WishlistListBundle_wishlistItem:
  pattern: /wishlistitem/{itemId}
  defaults: { _controller: WishlistListBundle:Wishlist:getItem }
    
WishlistListBundle_wishlistDelete:
  pattern: /wishlistdelete
  defaults: { _controller: WishlistListBundle:Wishlist:deleteWishlist }

WishlistListBundle_friendlist:
  pattern: /friendlist/{user_id}
  defaults: { _controller: WishlistListBundle:Friendlist:friendlist }
    
WishlistListBundle_purchaseItem:
  pattern: /purchaseItem
  defaults: { _controller: WishlistListBundle:Wishlist:purchaseItem }

WishlistListBundle_retractPurchases:
  pattern: /retractPurchases
  defaults: { _controller: WishlistListBundle:Shoppinglist:retractPurchases }
