WishlistListBundle_wishlistNew:
  pattern: /wishlistnew
  defaults: { _controller: WishlistListBundle:Wishlist:newWishlist }
  
WishlistListBundle_wishlistUpdate:
  pattern: /wishlistupdate
  defaults: { _controller: WishlistListBundle:Wishlist:updateWishlist }  

WishlistListBundle_wishlistItem:
  pattern: /wishlistitem/{itemId}
  defaults: { _controller: WishlistListBundle:Wishlist:getItem }

WishlistListBundle_itemSearch:
    pattern: /ItemSearch
    defaults: { _controller: WishlistListBundle:Wishlist:itemSearch }

#WishlistListBundle_itemSelect:
#    pattern: /ItemSelect
#    defaults: { _controller: WishlistListBundle:Wishlist:itemSelect }
    
WishlistListBundle_wishlistDelete:
  pattern: /wishlistdelete
  defaults: { _controller: WishlistListBundle:Wishlist:deleteWishlist }
    
WishlistListBundle_purchaseItem:
  pattern: /purchaseItem
  defaults: { _controller: WishlistListBundle:Wishlist:purchaseItem }

WishlistListBundle_retractPurchases:
  pattern: /retractPurchases
  defaults: { _controller: WishlistListBundle:Shoppinglist:retractPurchases }

WishlistListBundle_completeShoppingListItems:
  pattern: /completeShoppingListItems
  defaults: { _controller: WishlistListBundle:Shoppinglist:completeShoppingListItems }

WishlistListBundle_eventlist:
  pattern: /eventlist
  defaults: { _controller: WishlistListBundle:Eventlist:eventlist }

WishlistListBundle_grantedItemNotified:
  pattern: /grantedItemNotified
  defaults: { _controller: WishlistListBundle:Wishlist:grantedItemNotified }

