WishlistListBundle_wishlistNew:
  pattern: /wishlistnew
  defaults: { _controller: WishlistListBundle:Default:newWishlist }

WishlistListBundle_wishlistItem:
  pattern: /wishlistitem/{itemId}
  defaults: { _controller: WishlistListBundle:Default:getWishlistItem }
    
WishlistListBundle_wishlistDelete:
    pattern: /wishlistdelete
    defaults: { _controller: WishlistListBundle:Default:deleteWishlist }

WishlistListBundle_friendlist:
    pattern: /friendlist/{user_id}
    defaults: { _controller: WishlistListBundle:Default:friendlist }
    