parameters:
#    wishlist_list.example.class: Wishlist\ListBundle\Example

services:
#    wishlist_list.example:
#        class: %wishlist_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
