#wishlist:
#    pattern:  /wishlist/{wishlistuser_id}
#    defaults: { _controller: WishlistWishlistBundle:Default:index }
    
WishlistWishlistBundle_wishlistShow:
  pattern: /wishlist/{wishlistuser_id}
  defaults: { _controller: WishlistWishlistBundle:Default:show }
    
WishlistWishlistBundle_wishlistNew:
  pattern: /wishlistnew/{name}/{price}/{link}
  defaults: { _controller: WishlistWishlistBundle:Default:new }

WishlistWishlistBundle_wishlistItem:
  pattern: /wishlistitem/{itemId}
  defaults: { _controller: WishlistWishlistBundle:Default:getWishlistItem }
    
WishlistWishlistBundle_wishlistDelete:
    pattern: /wishlistdelete/{deletedItemName}
    defaults: { _controller: WishlistWishlistBundle:Default:delete }
