#wishlistItem:
#    pattern:  /wishlistitem/{wishlistitem_id}
#    defaults: { _controller: WishlistWishlistBundle:Default:getWishlistItem }
    
wishlist:
    pattern:  /wishlist/{wishlistuser_id}
    defaults: { _controller: WishlistWishlistBundle:Default:index }
