<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/21 16:47:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=wishlist',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
