Enum:
  columns:
    name: { type: string(255), notnull: true, unique: true }
    value: { type: integer, notnull: true }
    type: { type: string(255), notnull: true }

PendingUser:
  actAs: { Timestampable: ~ }
  columns:
    email: { type: string(255), notnull: true, unique: true }

WishlistUser:
  actAs: { Timestampable: ~ }
  columns:
    firstname: { type: string(255), notnull: true, unique: false }
    lastname: { type: string(255), notnull: true, unique: false }
    gender: { type: integer, notnull: false, default: 1 }
    birthdate: { type: datetime, notnull: true }
    email: { type: string(255), notnull: true }
    wishlistuser_id: { type: integer, autoincrement: true, primary: true }
    password: {type: string(255)}
  relations:
    Enum: { local: gender, foreign: value }

Friendship:
  tableName: friendships
  columns:
    usera_id: { type: integer, notnull: true }
    userb_id: { type: integer, notnull: true }

WishlistItem:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: false }
    price: { type: integer, notnull: true, unique: false }
    link: { type: string(255), notnull: true }
    is_public: { type: boolean, notnull: true, default: 1 }
    comment: { type: string(500), notnull: false}
    quantity: { type: integer, notnull: true, default: 1}
    user_id: { type: integer, notnull: true }
  indexes:
    item_user:
      fields: [name, price, link, user_id]
      type: unique  
  relations:
    WishlistUser: { onDelete: CASCADE, local: user_id, foreign: wishlistUser_id, foreignAlias: WishlistItems }

wishlist_update:
  columns: 
    template: { type: integer, notnull: true }
    type: { type: integer, notnull: true }   
    message: { type: string(255), notnull: true }
    datetime: { type: datetime, notnull: true }
    user_id : { type: integer }
  relations:
    WishlistUser: { onDelete: CASCADE, local: user_id, foreign: wishlistUser_id, foreignAlias: UserUpdates }
    
Events:
  columns:
    wishlistuser_id: { type: integer, notnull:true }
    event_date: { type: datetime, notnull: true }
    event_type: { type: integer, notnull:true }
  relations:
    WishlistUser: { onDelete: CASCADE, local: wishlistuser_id, foreign: wishlistUser_id, foreignAlias: UserEvents }
    