WishlistUser:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: false }
    gender: { type: integer, notnull: false, default: 1 }
    age: { type: integer, notnull: true, default: 18 }
    email: { type: string(255), notnull: true }
    wishlistuser_id: { type: integer, autoincrement: true, primary: true }
  relations:
    Enum: { local: gender, foreign: value }

Friendship:
  tableName: friendships
  columns:
    userA_id: { type: integer, notnull: true }
    userB_id: { type: integer, notnull: true }

WishlistItem:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    price: { type: integer, notnull: true, unique: false }
    is_public: { type: boolean, notnull: true, default: 1 }
    user_id: { type: integer, notnull: true }
  relations:
    WishlistUser: { onDelete: CASCADE, local: user_id, foreign: wishlistUser_id, foreignAlias: WishlistItems }

Enum:
  columns:
    name: { type: string(255), notnull: true, unique: true }
    value: { type: integer, notnull: true }
    