WishlistQABundle_gettingStarted:
    pattern:  /gettingStarted
    defaults: { _controller: WishlistQABundle:Default:gettingStarted }

WishlistQABundle_wishlistHelp:
    pattern:  /wishlistHelp
    defaults: { _controller: WishlistQABundle:Default:wishlistHelp }    

WishlistQABundle_help:
    pattern:  /help
    defaults: { _controller: WishlistQABundle:Default:help }
    
WishlistQABundle_contactSupport:
    pattern:  /contactSupport
    defaults: { _controller: WishlistQABundle:Default:contactSupport }
    
WishlistQABundle_resetpasswordrequest:
    pattern:  /resetpasswordrequest
    defaults: { _controller: WishlistQABundle:Default:resetpasswordrequest }    