WishlistQABundle_gettingStarted:
    pattern:  /gettingStarted
    defaults: { _controller: WishlistQABundle:Default:gettingStarted }

WishlistQABundle_wishlistHelp:
    pattern:  /wishlistHelp
    defaults: { _controller: WishlistQABundle:Default:wishlistHelp }
    
WishlistQABundle_shoppinglistHelp:
    pattern:  /shoppinglistHelp
    defaults: { _controller: WishlistQABundle:Default:shoppinglistHelp }

WishlistQABundle_eventsHelp:
    pattern:  /eventsHelp
    defaults: { _controller: WishlistQABundle:Default:eventsHelp }
    
WishlistQABundle_friendsHelp:
    pattern:  /friendsHelp
    defaults: { _controller: WishlistQABundle:Default:friendsHelp }

WishlistQABundle_updatesHelp:
    pattern:  /updatesHelp
    defaults: { _controller: WishlistQABundle:Default:updatesHelp }
    
WishlistQABundle_help:
    pattern:  /help
    defaults: { _controller: WishlistQABundle:Default:help }
    
WishlistQABundle_contactSupport:
    pattern:  /contactSupport
    defaults: { _controller: WishlistQABundle:Default:contactSupport }
    
WishlistQABundle__resetpasswordrequest:
    pattern:  /password/resetrequest
    defaults: { _controller: WishlistQABundle:Default:resetpasswordrequest }  
    
WishlistQABundle_forgotpassword:
  pattern: /password/forgotpassword/
  defaults: { _controller: WishlistQABundle:Default:ForgotPassword }
  
WishlistQABundle__savenewpassword:
  pattern: /password/save/
  defaults: { _controller: WishlistQABundle:Default:SaveNewPassword }
  
WishlistQABundle__submitnewpassword:
  pattern: /password/reset/
  defaults: { _controller: WishlistQABundle:Default:SubmitNewPassword }  
  