WishlistQABundle_gettingStarted:
    pattern:  /gettingStarted
    defaults: { _controller: WishlistQABundle:Default:gettingStarted }

WishlistQABundle_wishlistHelp:
    pattern:  /wishlistHelp
    defaults: { _controller: WishlistQABundle:Default:wishlistHelp }    
